In [1]:
%load_ext autoreload
%autoreload 2
%reset -f

In [2]:
from locallib.picarrodb import *
from locallib.slack import *
from locallib.etl import Loggers


import os
import sys
import pandas as pd
import geopandas as gpd
from pathlib import Path
from datetime import datetime, date, timedelta


# Find KPIHub root (directory containing lib/tables), then import lib.* as a package.
_here = Path.cwd().resolve()
_root = next((p for p in [_here, *list(_here.parents)[:12]] if (p / "lib" / "tables").is_dir()), None)
if _root is None:
    raise FileNotFoundError(
        f"Could not find KPIHub root (folder containing lib/tables). cwd={Path.cwd()!r}"
    )
sys.path.insert(0, str(_root))
os.chdir(_root)

from locallib.picarrodb import *
from locallib.slack import *
from locallib.etl import Loggers
from locallib.pandas import *

from lib.tables.IngesterTables import *
from lib.handlers.CustomerHandler import *
from lib.config import *
from lib.ingester.IngesterClass import Ingester
from lib.KPIHubConnection import *
from lib.query.bank import *
from lib.ingester.SurveySummaryIngester import *

EU1_Conn created successfully
EU2_Conn created successfully
DataHub_Conn created successfully
US_Conn created successfully
EU1_PROD_Conn created successfully
EU2_PROD_Conn created successfully

In [3]:
customer_list = get_customer_list(KPIHub_Conn)
arguments = {'conn': KPIHub_Conn}

customer_info = customer_list[customer_list['Name'] == 'PSG'].iloc[0]
customer_info
surveyIngester = SurveySummaryIngester(arguments)
surveyIngester.set_customer_info(customer_info)
surveyIngester.update_check()

In [13]:
reports = Query(f"SELECT * FROM KPI_ReportSummary WHERE CustomerId = '{customer_info['CustomerId']}'").execute(KPIHub_Conn)
reports.db.set_query("SELECT * FROM KPI_SurveySummary WHERE ReportId IN (SELECT ReportId FROM temp_report)")
rds = reports.db.execute(KPIHub_Conn, source_col = 'ReportId', temp_table_name = 'temp_report')
rds = rds[(rds['StartDay'] >= '2026-08-31') & (rds['StartDay'] <= '2026-09-06')]
# Find surveys that have repeated ReportId entries in rds
# (i.e., surveys that appear in more than one report if there are relevant columns)
if 'SurveyId' in rds.columns and 'ReportId' in rds.columns:
    # Count how many times each SurveyId appears with different ReportIds
    # If there are no reports for a SurveyId, nunique will be 0
    repeated_surveys = rds.groupby('SurveyId').agg(
        num_reports=('ReportId', 'nunique'),
        report_ids=('ReportId', list)
    )
    repeated_surveys = repeated_surveys[repeated_surveys['num_reports'] > 1]

else:
    print("rds does not have both SurveyId and ReportId columns; cannot check for repeated surveys.")

In [18]:
repeated_surveys.reset_index()['report_ids']

0    [FF674DE9-7605-8D03-4732-3A23793095C5, 67EDD62...
1    [8D804329-93CC-14E6-6EC7-3A2374070F6E, 29F41A9...
2    [FF674DE9-7605-8D03-4732-3A23793095C5, 67EDD62...
Name: report_ids, dtype: object

In [6]:
survey_id = repeated_surveys.index[1]  # take the first SurveyId with repeated reports
single_survey_df = pd.DataFrame({
    'SurveyId': [survey_id] * len(repeated_surveys.loc[survey_id, 'report_ids']),
    'ReportId': repeated_surveys.loc[survey_id, 'report_ids']
})
single_survey_df

                               SurveyId                              ReportId
0  053C2A1B-2746-2974-E69E-3A1FE90E0963  1289929A-230C-A37C-C990-3A1FEF76DAF6
1  053C2A1B-2746-2974-E69E-3A1FE90E0963  BEA12667-51E6-A92D-B09B-3A1FF38E2119

In [7]:
surveyIngester.data['reports_into'] = single_survey_df.copy()
surveyIngester.check_flag = True

In [8]:
surveyIngester.query_data()
proc_data = surveyIngester.data['output']
proc_data

,SurveyId,SurveyorUnit,SurveyRawDurationMinutes,SurveyDurationMinutes,ReportId,StartHour,StartTime,StartEpoch,EndTime,EndEpoch,...,TotalSegments,TotalKilometers,DayKilometers,NightKilometers,SegmentDurationMinutes,IdleTimeMinutes,ActiveTimeMinutes,AvgSpeedKm,SegmentWeight,LastUpdated
0,053C2A1B-2746-2974-E69E-3A1FE90E0963,PSG MSA car #1 - Ssanyong Torres,165.917733,126.780992,1289929A-230C-A37C-C990-3A1FEF76DAF6,8,08:33:44.653000,1.773132e+09,11:19:39.716999,1.773142e+09,...,230,45.620051,45.620051,0.0,127.513150,20.327383,107.185767,29.615760,0.764120,2026-09-08 12:57:04.712734
1,78E2D111-CA05-9C27-F3CA-3A1FEE0FA9B3,PSG MSA car #1 - Ssanyong Torres,152.891350,152.891350,1289929A-230C-A37C-C990-3A1FEF76DAF6,7,07:53:36.759000,1.773216e+09,10:26:30.240000,1.773225e+09,...,276,54.688236,54.688236,0.0,151.561667,21.582350,129.979317,28.537361,1.000000,2026-09-08 12:57:04.712734
2,48CCF2EB-FC7D-C2AC-6E8F-3A1EE75F4E0A,PSG MSA car #1 - Ssanyong Torres,58.862067,53.887808,BEA12667-51E6-A92D-B09B-3A1FF38E2119,7,07:40:25.825999,1.768808e+09,08:39:17.549999,1.768812e+09,...,65,12.753317,12.753317,0.0,50.709883,12.579883,38.130000,22.389855,0.915493,2026-09-08 12:57:04.712734
3,053C2A1B-2746-2974-E69E-3A1FE90E0963,PSG MSA car #1 - Ssanyong Torres,165.917733,41.341628,BEA12667-51E6-A92D-B09B-3A1FF38E2119,8,08:33:44.653000,1.773132e+09,11:19:39.716999,1.773142e+09,...,75,14.903985,14.903985,0.0,38.101683,2.106850,35.994833,28.418892,0.249169,2026-09-08 12:57:04.712734

In [9]:
proc_data.db.set_query('SELECT ReportId, ReportArea FROM KPI_ReportSummary WHERE ReportId IN (SELECT ReportId FROM temp_report)')
report = proc_data.db.execute(KPIHub_Conn, source_col = 'ReportId', temp_table_name = 'temp_report')
report_gdf = proc_data.db.execute(KPIHub_Conn, source_col = 'ReportId', temp_table_name = 'temp_report')
report_gdf["geometry"] = gpd.GeoSeries.from_wkt(report_gdf["ReportArea"])
report_gdf = gpd.GeoDataFrame(
    report_gdf,
    geometry="geometry",
    crs="EPSG:4326"
)
utm_crs = report_gdf.estimate_utm_crs()
report_gdf = report_gdf.to_crs(utm_crs)

In [10]:
# Check if both ReportIds have the same SurveyIds in proc_data
# Get the unique ReportIds from report_gdf
report_ids = report_gdf['ReportId'].unique()

# Filter proc_data for these ReportIds and get the corresponding SurveyIds
survey_ids_by_report = proc_data[proc_data['ReportId'].isin(report_ids)].groupby('ReportId')['SurveyId'].apply(set)

# Only proceed if there are exactly two ReportIds
if len(survey_ids_by_report) == 2:
    report_id_1, report_id_2 = survey_ids_by_report.index
    survey_ids_1 = survey_ids_by_report.loc[report_id_1]
    survey_ids_2 = survey_ids_by_report.loc[report_id_2]
    same_survey_ids = survey_ids_1 == survey_ids_2
    print(f"SurveyId sets for ReportId {report_id_1}: {survey_ids_1}")
    print(f"SurveyId sets for ReportId {report_id_2}: {survey_ids_2}")
    if same_survey_ids:
        print("Both ReportIds have the same SurveyIds.")
    else:
        print("ReportIds have different SurveyIds.")
else:
    print("There are not exactly two ReportIds to compare.")

SurveyId sets for ReportId 1289929A-230C-A37C-C990-3A1FEF76DAF6: {'78E2D111-CA05-9C27-F3CA-3A1FEE0FA9B3', '053C2A1B-2746-2974-E69E-3A1FE90E0963'}
SurveyId sets for ReportId BEA12667-51E6-A92D-B09B-3A1FF38E2119: {'053C2A1B-2746-2974-E69E-3A1FE90E0963', '48CCF2EB-FC7D-C2AC-6E8F-3A1EE75F4E0A'}
ReportIds have different SurveyIds.

In [11]:
import matplotlib.pyplot as plt
single_survey.db.set_query(query_segments_table(survey_table="#TempSurvey"))
segments = single_survey.db.execute(CONN_DICT[customer_info['DBLocation']], source_col = 'SurveyId', temp_table_name = '#TempSurvey')
segments.drop_duplicates(subset=['Id'], inplace=True)
segments_gdf = gpd.GeoDataFrame(
    segments,
    geometry=gpd.GeoSeries.from_wkt(segments['Shape']),
    crs="EPSG:4326"
)
# set it bew cremator
utm_crs = segments_gdf.estimate_utm_crs()
segments_gdf = segments_gdf.to_crs(utm_crs)
fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(1, 1, 1)
report_gdf.boundary.plot(ax=ax, color='red', linewidth=2)
segments_gdf.plot(ax=ax, color='orange', alpha=0.5)
ax.set_title('Report and Segment Layers')
ax.set_xlabel('Longitude')
ax.set_ylabel('Latitude')

NameError: name 'single_survey' is not defined

In [ ]:
report.db.set_query(get_report_info(report_table = '#TempReport'))
report_info = report.db.execute(EU1_Conn, source_col = 'ReportId', temp_table_name = '#TempReport')
report_info.head()

,CustomerName,ReportName,ReportId,ReportTitle,FinalCheckboxLabel,Labels,EarliestSurveyStart,EarliestSurveyEnd,LatestSurveyStart,LatestSurveyEnd,...,ReportArea,ReportAssetLengthKm,ReportPercentCoverageAssets,AssetCoveredLengthKm,DistributionPipeCoveredKm,DistributionPipeKm,DistributionPipePercentCovered,ServicePipeKm,ServicePipeCoveredKm,TimeZone
0,Gas Networks Ireland,CR-41CFB6,41CFB6BA-E019-4013-F20D-3A188EE8EB84,B25 - Phoenix Final 09102025,Final Checkbox,Final Checkbox,2025-03-03 19:33:41.580,2025-03-03 21:45:48.330,2025-03-04 20:54:05.720,2025-03-04 21:57:40.063,...,MULTIPOLYGON (((-6.3343210029891921 53.3460980...,42.913853,0.675184,28.974746,27.647185,39.460825,0.700624,3.453027,1.327561,W. Europe Standard Time
1,Gas Networks Ireland,CR-0D64CC,0D64CCC8-3F49-6835-1F57-3A1A7AA6379B,B25 - Phoenix Final 09102025-Gaps,Final Checkbox,Final Checkbox | emissions360,2025-03-03 19:33:41.580,2025-03-03 21:45:48.330,2025-03-04 20:54:05.720,2025-03-04 21:57:40.063,...,MULTIPOLYGON (((-6.3343210029891921 53.3460980...,42.913853,0.675188,28.974910,27.647344,39.460825,0.700628,3.453027,1.327566,W. Europe Standard Time