In [1]:
%load_ext autoreload
%autoreload 2
%reset -f

In [2]:
from pathlib import Path
import os
from os.path import join
import sys

# Find KPIHub root (directory containing lib/tables), then import lib.* as a package.
_here = Path.cwd().resolve()
_root = next((p for p in [_here, *list(_here.parents)[:12]] if (p / "lib" / "tables").is_dir()), None)
if _root is None:
    raise FileNotFoundError(
        f"Could not find KPIHub root (folder containing lib/tables). cwd={Path.cwd()!r}"
    )
sys.path.insert(0, str(_root))
os.chdir(_root)

from locallib.picarrodb import *
from locallib.slack import *
from locallib.etl import Loggers

from lib.tables.IngesterTables import *
from lib.handlers.CustomerHandler import *

from lib.config import *
from lib.KPIHubConnection import *
from lib.query.bank import *

from datetime import date
from datetime import timedelta

EU1_Conn created successfully
EU2_Conn created successfully
DataHub_Conn created successfully
US_Conn created successfully
EU1_PROD_Conn created successfully
EU2_PROD_Conn created successfully

In [3]:
customers = get_customer_list(KPIHub_Conn)

In [4]:
STARTING_DATE

datetime.date(2023, 1, 1)

In [5]:
df_kpi = Query(query = f"SELECT * FROM KPI_ReportSummary WHERE CustomerId = '{customers.iloc[0]['CustomerId']}'").execute(KPIHub_Conn)
df_kpi

,ReportId,CustomerId,ReportName,ReportDate,ReportYear,ReportMonth,ReportWeek,ReportAssetLengthKm,AssetCoveredLengthKm,DistributionPipeKm,...,ServicePipeKm,ServicePipeCoveredKm,BoundaryName,BoundaryType,BoundaryMode,BoundaryPlant,BoundarySubplant,BoundaryRegion,BoundarySubRegion,LastUpdated
0,99939D86-F073-F51B-8105-3A2233CD33EB,BD4D080B-1D12-D329-ABD0-39FEB9804E98,CR-99939D,2026-07-02 06:59:45.260000,2026,7,27,55.424546,52.420307,54.933812,...,0.490734,0.381136,B26 - 4963 - Stockport - Tameside - Hyde Werneth,SURVEY WARDS 2026,customer boundary,Stockport,None,North West,Tameside,2026-07-02 12:17:25.561578
1,E857B1E3-401C-2EF3-E3E1-3A222ECC743E,BD4D080B-1D12-D329-ABD0-39FEB9804E98,CR-E857B1,2026-07-01 07:40:50.110000,2026,7,27,54.074283,52.579579,53.497258,...,0.577025,0.531728,B26 - 9928 - South Yorkshire - Rotherham - Dal...,SURVEY WARDS 2026,customer boundary,South Yorkshire,None,East Midlands,Rotherham,2026-07-02 12:17:25.561578
2,0E746FF7-C56D-CF50-A8C8-3A2224704E2F,BD4D080B-1D12-D329-ABD0-39FEB9804E98,CR-0E746F,2026-06-29 07:23:58.897000,2026,6,27,51.456193,48.373915,50.993425,...,0.462768,0.305550,B26 - 8031 - Black Country - Sandwell - Hatele...,SURVEY WARDS 2026,customer boundary,Black Country,None,West Midlands,Sandwell,2026-07-02 12:17:25.561578
3,D473C751-99DA-D2B4-E8EA-3A21A3A45B65,BD4D080B-1D12-D329-ABD0-39FEB9804E98,CR-D473C7,2026-06-04 07:09:49.287000,2026,6,23,59.716786,57.478751,59.109445,...,0.607342,0.518206,B26 - 3732 - Bolton - Bury - Radcliffe North a...,SURVEY WARDS 2026,customer boundary,Bolton,None,North West,Bury,2026-07-02 12:17:25.561578
4,7CFD9363-43B7-7EC5-49B8-3A21F61AC3CB,BD4D080B-1D12-D329-ABD0-39FEB9804E98,CR-7CFD93,2026-06-20 07:28:00.970000,2026,6,25,11.437109,9.610690,10.758931,...,0.678178,0.351808,B26 - 6955 - Suffolk and Essex - Tendring - Do...,SURVEY WARDS 2026,customer boundary,Suffolk & Essex,None,East of England,Tendring,2026-07-02 12:17:25.561578
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3060,B336A10D-49E6-8D6F-AD9D-3A222ED62EF5,BD4D080B-1D12-D329-ABD0-39FEB9804E98,CR-B336A1,2026-07-01 07:51:27.733000,2026,7,27,12.815787,8.351407,12.394006,...,0.421781,0.182047,B26 - 6385 - WM South - Malvern Hills - Alfric...,SURVEY WARDS 2026,customer boundary,WM South,None,West Midlands,Malvern Hills,2026-07-02 12:17:25.561578
3061,A6D21D95-0B71-449B-FFC6-3A2233C797A2,BD4D080B-1D12-D329-ABD0-39FEB9804E98,CR-A6D21D,2026-07-02 06:53:37.570000,2026,7,27,52.624800,51.454768,52.195710,...,0.429090,0.372787,B26 - 9331 - Warrington - Wigan - Lowton East #1,SURVEY WARDS 2026,customer boundary,Warrington,None,North West,Wigan,2026-07-02 12:17:25.561578
3062,A4180063-676F-89D4-2537-3A2233C91120,BD4D080B-1D12-D329-ABD0-39FEB9804E98,CR-A41800,2026-07-02 06:55:14.210000,2026,7,27,5.550919,5.411548,5.544169,...,0.006750,0.006750,B26 - 6153 - Suffolk and Essex - West Suffolk ...,SURVEY WARDS 2026,customer boundary,Suffolk & Essex,None,East of England,West Suffolk,2026-07-02 12:17:25.561578
3063,2B038C8A-246F-CAD4-16E0-3A2233C9A4B4,BD4D080B-1D12-D329-ABD0-39FEB9804E98,CR-2B038C,2026-07-02 06:55:51.990000,2026,7,27,24.326306,23.476544,23.924726,...,0.401580,0.351841,B26 - 2249 - WM South - Malvern Hills - West,SURVEY WARDS 2026,customer boundary,WM South,None,West Midlands,Malvern Hills,2026-07-02 12:17:25.561578
3064,DEE0B7D6-F619-40BE-18E2-3A2233CDCACD,BD4D080B-1D12-D329-ABD0-39FEB9804E98,CR-DEE0B7,2026-07-02 07:00:23.887000,2026,7,27,31.053116,29.158504,29.913038,...,1.140078,0.861586,B26 - 6832 - Soar Valley - Harborough - Dunton,SURVEY WARDS 2026,customer boundary,Soar Valley,None,East Midlands,Harborough,2026-07-02 12:17:25.561578

In [9]:
query = f"""
    SELECT R.Id,
    R.DateStarted
    FROM Report R
    INNER JOIN ReportLabel RL ON RL.ReportId = R.Id
    INNER JOIN Label L ON RL.LabelId = L.Id
    WHERE R.CustomerId = '{customers.iloc[0]['CustomerId']}'
        AND R.DateStarted >= '{STARTING_DATE}'
        AND L.Title = 'Final Checkbox'
        AND RL.IsActive = 1
"""
print(query)

    SELECT R.Id,
    R.DateStarted
    FROM Report R
    INNER JOIN ReportLabel RL ON RL.ReportId = R.Id
    INNER JOIN Label L ON RL.LabelId = L.Id
    WHERE R.CustomerId = 'BD4D080B-1D12-D329-ABD0-39FEB9804E98'
        AND R.DateStarted >= '2023-01-01'
        AND L.Title = 'Final Checkbox'
        AND RL.IsActive = 1

In [10]:

lsdb_report_count = Query(query).execute(CONN_DICT[customers.iloc[0]['DBLocation']])
lsdb_report_count[~(lsdb_report_count['Id'].isin(df_kpi['ReportId']))]

Empty DataFrame
Columns: [Id, DateStarted]
Index: []

In [11]:
print(len(lsdb_report_count))
print(len(df_kpi))

3065
3065