In [1]:
%load_ext autoreload
%autoreload 2
%reset -f

In [2]:
from pathlib import Path
import os
from os.path import join
import sys
import sqlite3
# Find KPIHub root (directory containing lib/tables), then import lib.* as a package.
_here = Path.cwd().resolve()
_root = next((p for p in [_here, *list(_here.parents)[:12]] if (p / "lib" / "tables").is_dir()), None)
if _root is None:
    raise FileNotFoundError(
        f"Could not find KPIHub root (folder containing lib/tables). cwd={Path.cwd()!r}"
    )
sys.path.insert(0, str(_root))
os.chdir(_root)

from locallib.picarrodb import *
from locallib.slack import *
from locallib.etl import Loggers
from locallib.pandas import *

from lib.tables.IngesterTables import *
from lib.handlers.CustomerHandler import *
from lib.config import *
from lib.KPIHubConnection import *
from lib.query.bank import *

from datetime import date
from datetime import timedelta

EU1_Conn created successfully
EU2_Conn created successfully
DataHub_Conn created successfully
US_Conn created successfully

In [3]:
LOG_PATH = os.path.join(INGESTER_LOG_PATH, 'SurveySummaryIngester.log')
Logger = Loggers(logger_name = 'SurveySummaryIngester', keys = ['File', 'Slack'])
Logger.clear_handlers()
import logging

file_handler = logging.FileHandler(LOG_PATH)
# Set date format to dd-mm-yyyy in log output
formatter = logging.Formatter('%(asctime)s [%(levelname)s] %(name)s: %(message)s', datefmt='%d-%m-%Y')
file_handler.setFormatter(formatter)
Logger.File.addHandler(file_handler)

slack_handler = logging.StreamHandler(SlackWriter(channel = 'C0B9PGDNHH7'))
Logger.Slack.addHandler(slack_handler)

In [4]:
conn = sqlite3.connect(DB_PATH)
cursor = conn.cursor()
KPI_META_KEYS = [
        'ReportAssetLengthKm',
        'AssetCoveredLengthKm',
        'DistributionPipeKm',
        'DistributionPipeCoveredKm',
        'ServicePipeKm',
        'ServicePipeCoveredKm',
        'ReportCount',
        'DaysCount',
        'FOVMain',
        'SurveyDurationHours',
        'TargetDurationHours',
        'CustomerUtilization',
        'StarndardUtilization',
        'TotalSurveyors',
        'ProductivityPerSurveyor',
        'SurveyCount',
        'AvgSpeedKm',
        'SurveysCarDay',
        'IdleTime',
        'TotalDrivenLengthKm',
        'DrivingRatio',
        'NightDrivenLength',
        'DayDrivenLength',
        'NightRatio',
        'DayRatio',
        'LisaCount',
        'EmissionRate',
        'B0Count',
        'B1Count',
        'Bm1Count',
        'Bm2Count',
        'NGCount',
        'PGCount',
        'Not_NGCount',
        'LisaDensity',
        'InstatanoeusEmission',
        'B0Density',
        'B1Density',
        'B-1Density',
        'B-2Density',
        'B0Share',
        'B1Share',
        'B-1Share',
        'B-2Share',
        'NGShare',
        'PGShare',
        'Not_NGShare'
    ]

In [5]:
query = f"""DROP VIEW IF EXISTS Weekly_KPI;"""
cursor.execute(query)
conn.commit()

In [6]:
query = """
CREATE VIEW IF NOT EXISTS Weekly_KPI AS
SELECT
    kd.Year,
    kd.PeriodValue,
    kc.Name AS CustomerName,
    """ + ",\n    ".join([f"SUM(CASE WHEN kd.KPIId = '{kpi}' THEN kd.Value END) AS [{kpi}]" for kpi in KPI_META_KEYS]) + """
FROM KPI_Data kd
LEFT JOIN KPI_Customer kc ON kd.CustomerId = kc.CustomerId
WHERE kd.PeriodType = 'Weekly'
GROUP BY kd.Year, kd.PeriodValue, kd.CustomerId, kc.Name;"""
cursor.execute(query)
conn.commit()

In [7]:
query = "SELECT * FROM Weekly_KPI WHERE Year = 2026;"
df = pd.read_sql_query(query, conn)
conn.close()

In [8]:
df

,Year,PeriodValue,CustomerName,ReportAssetLengthKm,AssetCoveredLengthKm,DistributionPipeKm,DistributionPipeCoveredKm,ServicePipeKm,ServicePipeCoveredKm,ReportCount,...,B1Density,B-1Density,B-2Density,B0Share,B1Share,B-1Share,B-2Share,NGShare,PGShare,Not_NGShare
0,2026,1,Cadent,50.53,47.68,49.69,47.03,0.84,0.65,2.0,...,0.00,1.42,0.06,0.23,0.00,0.74,0.03,0.73,0.19,0.07
1,2026,2,Cadent,229.57,216.26,226.35,213.85,3.22,2.41,9.0,...,0.01,0.70,0.06,0.29,0.01,0.65,0.05,0.68,0.22,0.10
2,2026,3,Cadent,312.37,282.81,302.16,276.15,10.21,6.67,11.0,...,0.03,0.60,0.04,0.38,0.03,0.55,0.04,0.73,0.19,0.08
3,2026,4,Cadent,339.23,321.31,332.75,315.89,6.48,5.42,12.0,...,0.01,0.76,0.07,0.24,0.01,0.69,0.06,0.72,0.21,0.07
4,2026,5,Cadent,716.21,671.67,699.31,657.47,16.90,14.20,25.0,...,0.01,0.56,0.07,0.22,0.01,0.69,0.08,0.63,0.27,0.10
5,2026,6,Cadent,1530.09,1412.45,1491.98,1383.53,38.11,28.92,54.0,...,0.01,0.73,0.09,0.26,0.01,0.65,0.08,0.69,0.22,0.10
6,2026,7,Cadent,1442.95,1327.13,1408.33,1303.17,34.62,23.95,53.0,...,0.01,0.73,0.10,0.21,0.01,0.69,0.10,0.70,0.20,0.10
7,2026,8,Cadent,1647.92,1560.83,1618.80,1539.95,29.12,20.88,54.0,...,0.00,0.59,0.07,0.26,0.01,0.66,0.08,0.73,0.21,0.06
8,2026,9,Cadent,1466.42,1393.40,1435.40,1369.36,31.02,24.03,52.0,...,0.01,0.62,0.09,0.24,0.01,0.66,0.09,0.75,0.17,0.08
9,2026,10,Cadent,1210.19,1134.14,1191.31,1119.10,18.87,15.04,43.0,...,0.02,0.79,0.15,0.17,0.02,0.68,0.13,0.72,0.15,0.13
10,2026,11,Cadent,1250.23,1185.96,1221.88,1163.32,28.35,22.64,41.0,...,0.01,0.81,0.11,0.19,0.01,0.70,0.10,0.79,0.14,0.07
11,2026,12,Cadent,2016.91,1918.03,1967.17,1877.66,49.74,40.36,74.0,...,0.01,0.85,0.17,0.18,0.01,0.68,0.14,0.75,0.14,0.11
12,2026,13,Cadent,2873.27,2713.60,2806.45,2659.82,66.82,53.78,101.0,...,0.01,0.71,0.12,0.20,0.01,0.68,0.12,0.75,0.15,0.10
13,2026,14,Cadent,1927.57,1830.16,1889.15,1802.82,38.42,27.34,63.0,...,0.00,0.72,0.12,0.19,0.00,0.69,0.12,0.75,0.17,0.08
14,2026,15,Cadent,2673.67,2543.30,2608.00,2491.81,65.67,51.49,81.0,...,0.01,0.92,0.14,0.20,0.01,0.68,0.11,0.84,0.10,0.06
15,2026,16,Cadent,3695.66,3501.23,3606.84,3430.48,88.82,70.76,114.0,...,0.01,0.83,0.11,0.22,0.01,0.68,0.09,0.86,0.09,0.05
16,2026,17,Cadent,3889.88,3635.92,3785.82,3555.17,104.07,80.75,120.0,...,0.01,0.83,0.12,0.18,0.01,0.70,0.11,0.79,0.10,0.11
17,2026,18,Cadent,3572.83,3341.72,3483.54,3270.10,89.29,71.63,104.0,...,0.02,0.97,0.12,0.21,0.01,0.69,0.09,0.83,0.09,0.08
18,2026,19,Cadent,3072.31,2854.46,2981.94,2784.00,90.37,70.46,93.0,...,0.02,1.07,0.14,0.19,0.01,0.70,0.09,0.81,0.09,0.10
19,2026,20,Cadent,3440.95,3238.88,3357.38,3172.42,83.56,66.46,91.0,...,0.01,1.05,0.18,0.18,0.01,0.69,0.12,0.82,0.10,0.08
20,2026,21,Cadent,3228.47,3011.75,3150.10,2949.47,78.38,62.28,97.0,...,0.01,0.93,0.15,0.21,0.01,0.67,0.11,0.83,0.09,0.08
21,2026,22,Cadent,2911.85,2737.27,2825.18,2668.99,86.67,68.28,81.0,...,0.02,1.07,0.15,0.23,0.01,0.67,0.09,0.78,0.10,0.12
22,2026,23,Cadent,3455.50,3231.83,3376.26,3171.70,79.24,60.12,104.0,...,0.03,0.71,0.10,0.24,0.02,0.65,0.09,0.77,0.11,0.12
23,2026,24,Cadent,3108.91,2923.05,3035.30,2868.33,73.61,54.72,91.0,...,0.02,0.76,0.11,0.21,0.02,0.68,0.10,0.79,0.11,0.09
24,2026,25,Cadent,3157.42,2979.87,3074.96,2913.74,82.46,66.13,95.0,...,0.01,1.08,0.15,0.20,0.01,0.69,0.10,0.82,0.09,0.09
25,2026,26,Cadent,405.53,370.75,390.62,359.19,14.91,11.57,13.0,...,0.04,1.08,0.13,0.21,0.02,0.68,0.08,0.74,0.12,0.14

In [9]:
df.to_excel("pivot_view.xlsx")

In [10]:
Query(query = f"SELECT * FROM KPI_Data WHERE Year = 2026 AND PeriodValue = '23' AND CustomerId = (SELECT CustomerId FROM KPI_Customer WHERE Name = 'Cadent')").execute(KPIHub_Conn)

,Id,KPIId,CustomerId,Year,PeriodType,PeriodValue,Value,DataType,LastUpdated
0,FOVMain_Cadent_Y2026_W23,FOVMain,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,0.94,None,2026-06-22 09:57:37.990053
1,ReportAssetLengthKm_Cadent_Y2026_W23,ReportAssetLengthKm,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,3455.5,None,2026-06-22 09:57:37.990053
2,AssetCoveredLengthKm_Cadent_Y2026_W23,AssetCoveredLengthKm,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,3231.83,None,2026-06-22 09:57:37.990053
3,DistributionPipeKm_Cadent_Y2026_W23,DistributionPipeKm,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,3376.26,None,2026-06-22 09:57:37.990053
4,DistributionPipeCoveredKm_Cadent_Y2026_W23,DistributionPipeCoveredKm,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,3171.7,None,2026-06-22 09:57:37.990053
5,ServicePipeKm_Cadent_Y2026_W23,ServicePipeKm,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,79.24,None,2026-06-22 09:57:37.990053
6,ServicePipeCoveredKm_Cadent_Y2026_W23,ServicePipeCoveredKm,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,60.12,None,2026-06-22 09:57:37.990053
7,ReportCount_Cadent_Y2026_W23,ReportCount,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,104.0,None,2026-06-22 09:57:37.990053
8,LisaCount_Cadent_Y2026_W23,LisaCount,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,3498.0,None,2026-06-22 09:58:07.100715
9,EmissionRate_Cadent_Y2026_W23,EmissionRate,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,5423.78,None,2026-06-22 09:58:07.100715
10,B0Count_Cadent_Y2026_W23,B0Count,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,854.0,None,2026-06-22 09:58:07.100715
11,B1Count_Cadent_Y2026_W23,B1Count,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,83.0,None,2026-06-22 09:58:07.100715
12,Bm1Count_Cadent_Y2026_W23,Bm1Count,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,2258.0,None,2026-06-22 09:58:07.100715
13,Bm2Count_Cadent_Y2026_W23,Bm2Count,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,303.0,None,2026-06-22 09:58:07.100715
14,NGCount_Cadent_Y2026_W23,NGCount,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,3055.0,None,2026-06-22 09:58:07.100715
15,PGCount_Cadent_Y2026_W23,PGCount,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,443.0,None,2026-06-22 09:58:07.100715
16,Not_NGCount_Cadent_Y2026_W23,Not_NGCount,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,479.0,None,2026-06-22 09:58:07.100715
17,LisaDensity_Cadent_Y2026_W23,LisaDensity,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,1.1,None,2026-06-22 09:58:07.100715
18,InstatanoeusEmission_Cadent_Y2026_W23,InstatanoeusEmission,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,1.71,None,2026-06-22 09:58:07.100715
19,B0Density_Cadent_Y2026_W23,B0Density,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,0.27,None,2026-06-22 09:58:07.100715
20,B1Density_Cadent_Y2026_W23,B1Density,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,0.03,None,2026-06-22 09:58:07.100715
21,B-1Density_Cadent_Y2026_W23,B-1Density,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,0.71,None,2026-06-22 09:58:07.100715
22,B-2Density_Cadent_Y2026_W23,B-2Density,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,0.1,None,2026-06-22 09:58:07.100715
23,NGDensity_Cadent_Y2026_W23,NGDensity,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,0.96,None,2026-06-22 09:58:07.100715
24,PGDensity_Cadent_Y2026_W23,PGDensity,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,0.14,None,2026-06-22 09:58:07.100715
25,B0Share_Cadent_Y2026_W23,B0Share,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,0.24,None,2026-06-22 09:58:07.100715
26,B1Share_Cadent_Y2026_W23,B1Share,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,0.02,None,2026-06-22 09:58:07.100715
27,B-1Share_Cadent_Y2026_W23,B-1Share,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,0.65,None,2026-06-22 09:58:07.100715
28,B-2Share_Cadent_Y2026_W23,B-2Share,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,0.09,None,2026-06-22 09:58:07.100715
29,NGShare_Cadent_Y2026_W23,NGShare,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,0.77,None,2026-06-22 09:58:07.100715
30,PGShare_Cadent_Y2026_W23,PGShare,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,0.11,None,2026-06-22 09:58:07.100715
31,Not_NGShare_Cadent_Y2026_W23,Not_NGShare,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,0.12,None,2026-06-22 09:58:07.100715
32,SurveyDurationHours_Cadent_Y2026_W23,SurveyDurationHours,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,1036.05,None,2026-06-22 09:58:21.959676
33,TargetDurationHours_Cadent_Y2026_W23,TargetDurationHours,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,1127.0,None,2026-06-22 09:58:21.959676
34,CustomerUtilization_Cadent_Y2026_W23,CustomerUtilization,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,0.92,None,2026-06-22 09:58:21.959676
35,StarndardUtilization_Cadent_Y2026_W23,StarndardUtilization,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,1.38,None,2026-06-22 09:58:21.959676
36,TotalSurveyors_Cadent_Y2026_W23,TotalSurveyors,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,23.0,None,2026-06-22 09:58:21.959676
37,ProductivityPerSurveyor_Cadent_Y2026_W23,ProductivityPerSurveyor,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,137.9,None,2026-06-22 09:58:21.959676
38,SurveyCount_Cadent_Y2026_W23,SurveyCount,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,581.0,None,2026-06-22 09:58:21.959676
39,AvgSpeedKm_Cadent_Y2026_W23,AvgSpeedKm,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,24.44,None,2026-06-22 09:58:21.959676
40,SurveysCarDay_Cadent_Y2026_W23,SurveysCarDay,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,3.61,None,2026-06-22 09:58:21.959676
41,IdleTime_Cadent_Y2026_W23,IdleTime,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,14.91,None,2026-06-22 09:58:21.959676
42,TotalDrivenLengthKm_Cadent_Y2026_W23,TotalDrivenLengthKm,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,15522.72,None,2026-06-22 09:58:21.959676
43,DrivingRatio_Cadent_Y2026_W23,DrivingRatio,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,4.8,None,2026-06-22 09:58:21.959676
44,NightDrivenLength_Cadent_Y2026_W23,NightDrivenLength,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,15481.83,None,2026-06-22 09:58:21.959676
45,DayDrivenLength_Cadent_Y2026_W23,DayDrivenLength,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,40.88,None,2026-06-22 09:58:21.959676
46,NightRatio_Cadent_Y2026_W23,NightRatio,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,99.74,None,2026-06-22 09:58:21.959676
47,DayRatio_Cadent_Y2026_W23,DayRatio,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,Weekly,23,0.26,None,2026-06-22 09:58:21.959676