In [1]:
%load_ext autoreload
%autoreload 2
%reset -f

In [2]:
from pathlib import Path
import os
from os.path import join
import sys
import sqlite3
# Find KPIHub root (directory containing lib/tables), then import lib.* as a package.
_here = Path.cwd().resolve()
_root = next((p for p in [_here, *list(_here.parents)[:12]] if (p / "lib" / "tables").is_dir()), None)
if _root is None:
    raise FileNotFoundError(
        f"Could not find KPIHub root (folder containing lib/tables). cwd={Path.cwd()!r}"
    )
sys.path.insert(0, str(_root))
os.chdir(_root)

from locallib.picarrodb import *
from locallib.slack import *
from locallib.etl import Loggers
from locallib.pandas import *

from lib.tables.IngesterTables import *
from lib.handlers.CustomerHandler import *
from lib.config import *
from lib.KPIHubConnection import *
from lib.query.bank import *
from lib.kpi_processor.KPIReportEurope import *
from datetime import date
from datetime import timedelta

EU1_Conn created successfully
EU2_Conn created successfully
DataHub_Conn created successfully
US_Conn created successfully
EU1_PROD_Conn created successfully
EU2_PROD_Conn created successfully

In [3]:
conn = sqlite3.connect(DB_PATH)
cursor = conn.cursor()
KPI_META_KEYS = KPIReport.kpi_list + KPIEmissionSource.kpi_list

In [4]:
cursor.execute("DROP VIEW IF EXISTS Country_Yearly_KPI;")
cursor.execute("DROP VIEW IF EXISTS Customer_Yearly_KPI;")
conn.commit()

In [5]:
query = """
CREATE VIEW IF NOT EXISTS Country_Yearly_KPI AS
SELECT
    kd.Year,
    kc.Name AS Country,
    """ + ",\n    ".join([f"SUM(CASE WHEN kd.KPIId = '{kpi}' THEN kd.Value END) AS [{kpi}]" for kpi in KPI_META_KEYS]) + """
FROM KPI_Data kd
INNER JOIN KPI_Country kc ON kd.CustomerId = kc.CountryId
WHERE kd.PeriodType = 'Year'
GROUP BY kd.Year, kd.CustomerId, kc.Name;"""
cursor.execute(query)

query = """
CREATE VIEW IF NOT EXISTS Customer_Yearly_KPI AS
SELECT
    kd.Year,
    kc.Name AS CustomerName,
    kc.Country AS Country,
    """ + ",\n    ".join([f"SUM(CASE WHEN kd.KPIId = '{kpi}' THEN kd.Value END) AS [{kpi}]" for kpi in KPI_META_KEYS]) + """
FROM KPI_Data kd
INNER JOIN KPI_Customer kc ON kd.CustomerId = kc.CustomerId
WHERE kd.PeriodType = 'Year'
GROUP BY kd.Year,kd.CustomerId, kc.Name;"""
cursor.execute(query)

conn.commit()

In [6]:
query = "SELECT * FROM Country_Yearly_KPI WHERE Year = 2026;"
query_customer = "SELECT * FROM Customer_Yearly_KPI WHERE Year = 2026;"
country_df = pd.read_sql_query(query, conn)
customer_df = pd.read_sql_query(query_customer, conn)
conn.close()
display(country_df)
display(customer_df)

,Year,Country,FOVMain,ReportAssetLengthKm,AssetCoveredLengthKm,DistributionPipeKm,DistributionPipeCoveredKm,ServicePipeKm,ServicePipeCoveredKm,ReportCount,...,Bm2Density,NGDensity,PGDensity,B0Share,B1Share,Bm1Share,Bm2Share,NGShare,PGShare,Not_NGShare
0,2026,United Kingdom,94.31,79435.57,74611.26,77516.83,73103.40,1918.74,1507.87,2478.0,...,0.13,1.10,0.18,20.00,1.02,68.82,10.15,76.05,12.72,11.23
1,2026,Italy,91.89,200558.85,184093.34,199462.50,183276.67,1096.35,816.67,4162.0,...,0.22,0.69,0.50,13.39,0.50,67.74,18.36,43.99,31.88,24.14
2,2026,Romania,94.66,183.72,174.11,162.63,153.94,21.10,20.17,7.0,...,0.49,1.11,1.68,17.08,1.65,63.58,17.70,38.88,58.52,2.61
3,2026,Switzerland,97.57,178.63,174.14,125.69,122.63,52.94,51.51,3.0,...,0.03,0.57,0.17,32.81,1.56,61.72,3.91,73.88,21.64,4.48
4,2026,Greece,99.36,16665.23,16564.50,14279.27,14187.86,2385.97,2376.64,404.0,...,0.27,0.78,0.50,10.75,0.42,68.06,20.77,46.73,30.00,23.26
5,2026,Germany,92.48,34089.17,31602.80,23325.63,21571.45,10763.60,10031.40,1477.0,...,0.04,0.10,0.15,16.00,0.93,67.62,15.45,17.95,26.94,55.12
6,2026,Poland,37.82,4127.24,1560.89,4127.24,1560.89,0.00,0.00,114.0,...,0.04,0.25,0.26,40.61,2.14,50.19,7.06,31.02,31.42,37.56
7,2026,Austria,39.64,185.12,65.20,146.00,57.87,39.13,7.33,42.0,...,0.03,0.05,0.21,0.00,0.00,88.24,11.76,7.89,36.84,55.26
8,2026,Ireland,95.27,4420.82,4190.69,4225.02,4025.13,195.81,165.56,131.0,...,0.02,0.13,0.05,26.69,1.36,63.14,8.81,38.10,15.46,46.44
9,2026,Netherlands,94.14,1073.16,1009.69,710.45,668.79,362.71,340.90,38.0,...,0.06,0.17,0.36,27.72,2.62,58.80,10.86,13.98,28.92,57.11

,Year,CustomerName,Country,FOVMain,ReportAssetLengthKm,AssetCoveredLengthKm,DistributionPipeKm,DistributionPipeCoveredKm,ServicePipeKm,ServicePipeCoveredKm,...,Bm2Density,NGDensity,PGDensity,B0Share,B1Share,Bm1Share,Bm2Share,NGShare,PGShare,Not_NGShare
0,2026,Wales and West Utilities,United Kingdom,92.99,2572.39,2392.00,2572.39,2392.00,0.00,0.00,...,0.18,1.57,0.40,22.97,1.29,66.53,9.22,74.39,18.94,6.66
1,2026,APRETIGAS,Italy,90.95,14783.39,13452.61,14498.15,13186.65,285.24,265.97,...,0.21,0.76,0.49,16.10,0.55,66.85,16.50,43.91,27.98,28.10
2,2026,ADRIGAS,Italy,95.54,774.91,739.87,765.20,731.09,9.71,8.78,...,0.08,0.44,0.43,29.68,2.78,58.73,8.81,50.85,49.15,0.00
3,2026,M Reti,Italy,99.94,84.40,84.35,84.40,84.35,0.00,0.00,...,0.57,1.74,1.77,12.50,0.00,71.28,16.22,32.81,33.26,33.93
4,2026,CPL CONCORDIA,Romania,94.66,183.72,174.11,162.63,153.94,21.10,20.17,...,0.49,1.11,1.68,17.08,1.65,63.58,17.70,38.88,58.52,2.61
5,2026,RETEGAS BARI spa,Italy,96.17,170.15,163.63,170.15,163.63,0.00,0.00,...,0.35,1.04,0.68,17.38,0.35,62.06,20.21,52.15,34.36,13.50
6,2026,ASTEA,Italy,95.36,177.86,169.61,177.86,169.61,0.00,0.00,...,0.14,0.95,0.48,23.05,1.65,65.43,9.88,62.40,31.78,5.81
7,2026,AIL,Switzerland,97.57,178.63,174.14,125.69,122.63,52.94,51.51,...,0.03,0.57,0.17,32.81,1.56,61.72,3.91,73.88,21.64,4.48
8,2026,Centria,Italy,98.68,212.17,209.37,212.17,209.37,0.00,0.00,...,0.14,0.62,0.35,10.40,0.00,75.25,14.36,43.43,24.58,31.99
9,2026,DEPA,Greece,99.36,16665.23,16564.50,14279.27,14187.86,2385.97,2376.64,...,0.27,0.78,0.50,10.75,0.42,68.06,20.77,46.73,30.00,23.26
10,2026,Condotte Nord,Italy,95.65,70.03,66.98,70.03,66.98,0.00,0.00,...,0.30,1.54,0.40,13.85,0.00,70.77,15.38,73.57,19.29,7.14
11,2026,RETI PIU,Italy,53.12,6454.58,3411.47,5986.05,3179.97,468.53,231.50,...,0.15,0.45,0.31,9.51,0.23,70.20,20.06,41.99,29.24,28.77
12,2026,CBL Distribuzione,Italy,95.71,96.37,92.23,96.37,92.23,0.00,0.00,...,0.35,0.95,0.62,8.28,0.69,68.97,22.07,45.60,29.53,24.87
13,2026,Retragas,Italy,90.90,394.17,355.96,384.81,349.78,9.36,6.18,...,0.06,0.49,0.19,29.51,0.41,61.89,8.20,58.47,22.59,18.94
14,2026,AES Fano,Italy,98.35,94.72,93.17,94.72,93.17,0.00,0.00,...,0.06,0.19,0.53,20.90,1.49,68.66,8.96,16.51,44.95,38.53
15,2026,Energieversorgung Filstal,Germany,96.45,1384.93,1331.80,982.44,947.57,402.49,384.23,...,0.05,0.16,0.17,15.94,0.69,69.52,13.86,24.54,25.35,50.12
16,2026,GERGAS,Italy,97.43,131.30,127.92,131.30,127.92,0.00,0.00,...,0.10,0.54,0.57,22.54,0.70,67.61,9.15,34.85,36.87,28.28
17,2026,MEGARETI,Italy,67.13,3854.41,2592.62,3829.08,2570.37,25.33,22.25,...,0.22,0.89,0.40,17.52,0.87,64.64,16.98,54.51,24.43,21.06
18,2026,PSG,Poland,35.23,3767.26,1327.04,3767.26,1327.04,0.00,0.00,...,0.03,0.27,0.19,39.77,2.13,51.55,6.55,51.42,35.13,13.46
19,2026,Netz Niederösterreich,Austria,39.64,185.12,65.20,146.00,57.87,39.13,7.33,...,0.03,0.05,0.21,0.00,0.00,88.24,11.76,7.89,36.84,55.26
20,2026,Reti Di Voghera,Italy,99.22,77.65,77.04,77.65,77.04,0.00,0.00,...,0.31,0.60,0.92,7.69,0.00,71.79,20.51,26.44,40.80,32.76
21,2026,EWE,Germany,89.68,5920.54,5290.74,3928.38,3523.14,1992.17,1767.60,...,0.04,0.05,0.25,25.43,1.77,60.72,12.08,4.40,21.57,74.03
22,2026,ENBW,Germany,91.99,3953.95,3682.73,2858.43,2629.41,1095.54,1053.35,...,0.04,0.09,0.10,10.22,0.42,68.07,21.29,28.27,32.34,39.39
23,2026,G.EN Operator,Poland,64.96,359.98,233.85,359.98,233.85,0.00,0.00,...,0.07,0.13,0.65,43.41,2.20,45.60,8.79,5.50,26.77,67.73
24,2026,Salerno Energia,Italy,97.36,555.90,541.24,555.90,541.24,0.00,0.00,...,0.18,0.97,0.62,17.72,0.70,70.05,11.54,43.21,27.41,29.38
25,2026,Syna,Germany,98.42,824.49,810.11,562.01,553.11,262.48,256.99,...,0.07,0.07,0.18,7.96,1.49,63.18,27.36,14.61,36.02,49.37
26,2026,Server SRL,Italy,97.27,61.95,60.26,61.95,60.26,0.00,0.00,...,0.27,1.08,0.53,15.46,0.00,68.04,16.49,58.56,28.83,12.61
27,2026,Unareti,Italy,97.05,3576.59,3471.25,3576.59,3471.25,0.00,0.00,...,0.24,0.58,0.83,11.68,0.41,70.71,17.21,28.67,41.14,30.19
28,2026,V Reti Spoleto,Italy,94.69,872.80,826.43,872.80,826.43,0.00,0.00,...,0.23,1.56,0.26,21.53,1.47,64.60,12.40,81.88,13.48,4.64
29,2026,NBB,Germany,93.54,5963.85,5552.91,4201.85,3930.40,1762.00,1622.52,...,0.04,0.19,0.12,13.69,0.68,72.22,13.41,42.15,26.46,31.39
30,2026,Reti-MT,Italy,93.88,1288.96,1210.04,1288.96,1210.04,0.00,0.00,...,0.09,0.43,0.30,22.15,0.45,64.77,12.64,43.19,30.21,26.60
31,2026,Gas Networks Ireland,Ireland,95.27,4420.82,4190.69,4225.02,4025.13,195.81,165.56,...,0.02,0.13,0.05,26.69,1.36,63.14,8.81,38.10,15.46,46.44
32,2026,Thuega Energienetze,Germany,95.40,2062.78,1972.31,1364.48,1301.70,698.30,670.61,...,0.03,0.12,0.13,17.39,0.83,67.70,14.08,28.75,30.09,41.17
33,2026,Toscana Energia,Italy,93.80,11876.62,11140.73,11876.62,11140.73,0.00,0.00,...,0.24,0.69,0.64,11.25,0.40,70.41,17.94,41.18,38.10,20.72
34,2026,Aemme,Italy,9.91,237.58,23.54,237.58,23.54,0.00,0.00,...,2.00,1.61,5.65,6.43,1.17,64.91,27.49,13.24,46.34,40.42
35,2026,Cadent,United Kingdom,94.35,76863.18,72219.26,74944.44,70711.39,1918.74,1507.87,...,0.13,1.09,0.18,19.85,1.01,68.94,10.20,76.13,12.41,11.46
36,2026,Gigas Rete,Italy,96.07,183.85,176.63,183.85,176.63,0.00,0.00,...,0.22,0.55,0.82,18.52,0.82,65.02,15.64,24.94,36.90,38.17
37,2026,Westnetz,Germany,97.53,2366.35,2302.55,1627.17,1587.01,739.18,715.54,...,0.05,0.06,0.16,8.45,0.59,67.19,23.77,11.42,31.32,57.26
38,2026,MEA,Italy,99.42,41.41,41.17,41.41,41.17,0.00,0.00,...,0.29,1.14,0.66,12.16,0.00,71.62,16.22,56.63,32.53,10.84
39,2026,ITALGAS,Italy,93.82,152196.62,142797.92,152196.62,142797.92,0.00,0.00,...,0.22,0.69,0.49,13.12,0.49,67.61,18.79,44.55,31.74,23.71
40,2026,GP Infrastrutture,Italy,86.54,130.15,112.63,130.15,112.63,0.00,0.00,...,0.17,0.41,0.52,13.33,0.95,67.62,18.10,29.11,37.34,33.54
41,2026,SNAM,Italy,2.62,12.07,0.32,12.07,0.32,0.00,0.00,...,0.00,6.33,3.16,100.00,0.00,0.00,0.00,50.00,25.00,25.00
42,2026,GEI spa,Italy,97.37,1368.45,1332.03,1269.06,1235.67,99.38,96.35,...,0.19,0.38,0.53,10.96,0.25,67.77,21.02,22.15,31.48,46.37
43,2026,E-NETZ SUDHESSEN,Germany,83.26,3591.67,3122.11,2458.07,2046.65,1133.60,1075.46,...,0.05,0.08,0.18,9.54,0.37,70.26,19.83,17.94,38.61,43.45
44,2026,GESAM,Italy,96.85,569.20,544.37,370.39,358.74,198.81,185.63,...,0.15,0.36,0.32,7.32,0.00,71.27,21.41,44.17,38.57,17.26
45,2026,Avacon,Germany,94.57,8020.61,7537.54,5342.81,5052.46,2677.83,2485.10,...,0.02,0.08,0.11,18.30,1.04,68.06,12.60,18.90,27.21,53.90
46,2026,RETI Distribuzione,Italy,84.48,210.60,177.93,210.60,177.93,0.00,0.00,...,0.25,0.80,0.52,17.52,0.00,63.68,18.80,45.08,29.21,25.71
47,2026,Stedin,Netherlands,94.14,1073.16,1009.69,710.45,668.79,362.71,340.90,...,0.06,0.17,0.36,27.72,2.62,58.80,10.86,13.98,28.92,57.11

In [7]:
KPIEmissionSource.kpi_list

['LisaCount',
 'LisaPSCount',
 'EmissionRate',
 'B0Count',
 'B1Count',
 'Bm1Count',
 'Bm2Count',
 'NGCount',
 'PGCount',
 'Not_NGCount',
 'EmissionRateLPM',
 'RepresentativeEmissionRate',
 'RepresentativeEmissionRateLPM',
 'B0RepEmissionRateLPM',
 'B1RepEmissionRateLPM',
 'Bm1RepEmissionRateLPM',
 'Bm2RepEmissionRateLPM',
 'B0RepEmissionRate',
 'B1RepEmissionRate',
 'Bm1RepEmissionRate',
 'Bm2RepEmissionRate',
 'LisaDensity',
 'InstantaneousEmission',
 'InstantaneousEmissionLPM',
 'InstantaneousRepEmission',
 'InstantaneousRepEmissionLPM',
 'InstantaneousRepEmissionB1',
 'InstantaneousRepEmissionB1LPM',
 'InstantaneousRepEmissionB0',
 'InstantaneousRepEmissionB0LPM',
 'InstantaneousRepEmissionBm1',
 'InstantaneousRepEmissionBm1LPM',
 'InstantaneousRepEmissionBm2',
 'InstantaneousRepEmissionBm2LPM',
 'B0Density',
 'B1Density',
 'Bm1Density',
 'Bm2Density',
 'NGDensity',
 'PGDensity',
 'B0Share',
 'B1Share',
 'Bm1Share',
 'Bm2Share',
 'NGShare',
 'PGShare',
 'Not_NGShare']