In [2]:
%load_ext autoreload
%autoreload 2
%reset -f

In [3]:
from pathlib import Path
import os
from os.path import join
import sys

# Find KPIHub root (directory containing lib/tables), then import lib.* as a package.
_here = Path.cwd().resolve()
_root = next((p for p in [_here, *list(_here.parents)[:12]] if (p / "lib" / "tables").is_dir()), None)
if _root is None:
    raise FileNotFoundError(
        f"Could not find KPIHub root (folder containing lib/tables). cwd={Path.cwd()!r}"
    )
sys.path.insert(0, str(_root))
os.chdir(_root)

from locallib.picarrodb import *
from locallib.slack import *
from locallib.etl import Loggers
from locallib.pandas import *
from locallib.box import *

from lib.tables.IngesterTables import *
from lib.handlers.CustomerHandler import *
from lib.config import *
from lib.KPIHubConnection import *
from lib.query.bank import *

from datetime import date
from datetime import timedelta

EU1_Conn created successfully
EU2_Conn created successfully
DataHub_Conn created successfully
US_Conn created successfully
EU1_PROD_Conn created successfully
EU2_PROD_Conn created successfully

In [4]:
Query(query = "SELECT * FROM KPI_PeakAboveSAT").execute(KPIHub_Conn)

,CustomerId,PeakName,PeakId,Date,ReportYear,WeekNumber,Disposition,LocalTime,BoundaryName,BoundaryRegion,EmissionRate,PeakGpsLatitude,PeakGpsLongitude,Easting,Northing,UserName,SurveyorUnit,AnalyzerSerialNumber,Hyperlink,LastUpdated
0,BD4D080B-1D12-D329-ABD0-39FEB9804E98,P6B43EB,6B43EB72-6407-481E-AED4-B10A13FE2CA4,2026-07-08 00:00:00,2026,28,1,04:20:02,B26 - 9607 - Warrington - St. Helens - Haydock #1,North West,41.692215,53.472544,-2.686435,354534.037913,397531.791999,Glynn.Evans@cadentgas.com,Cadent Surveyor #06 - LM75XVG,RFADS2357,https://pcubed2.eu.picarro.com/Live/Survey/1b9...,2026-07-08 23:34:20.761871
1,BD4D080B-1D12-D329-ABD0-39FEB9804E98,P225B6C,225B6CD7-31F0-4CFE-9AB9-C4052594305E,2026-07-08 00:00:00,2026,28,1,03:48:58,B26 - 2218 - Derwent - East Staffordshire - Et...,East Midlands,21.318378,52.825858,-1.619926,425707.304841,325437.475314,rav.khaira@cadentgas.com,Cadent Surveyor #11 - LL75ZZJ,RFADS2094,https://pcubed2.eu.picarro.com/Live/Survey/d34...,2026-07-08 23:34:20.761871
2,BD4D080B-1D12-D329-ABD0-39FEB9804E98,P9842F8,9842F877-EEA2-43F2-B318-39FC1178AD34,2026-07-08 00:00:00,2026,28,1,03:29:30,B26 - 9586 - Cambridgeshire - South Cambridges...,East of England,43.368294,52.194669,0.199963,550464.888469,257439.955561,alan.lee@cadentgas.com,Cadent Surveyor #07 - LO75SWX,RFADS2361,https://pcubed2.eu.picarro.com/Live/Survey/5eb...,2026-07-08 23:34:20.761871
3,BD4D080B-1D12-D329-ABD0-39FEB9804E98,P72D2F4,72D2F44C-0B0F-4D04-BD60-122A700FF257,2026-07-08 00:00:00,2026,28,1,03:04:36,B26 - 5209 - Bolton - Oldham - St Marys,North West,22.490378,53.546215,-2.099616,393496.670650,405513.209046,Dean.Pilkington@cadentgas.com,Cadent Surveyor #23 - LM75YJF,RFADS2413,https://pcubed2.eu.picarro.com/Live/Survey/a79...,2026-07-08 23:34:20.761871
4,BD4D080B-1D12-D329-ABD0-39FEB9804E98,P8DDD4F,8DDD4F7C-CA53-4F6D-9A3E-A06E2C4981B5,2026-07-08 00:00:00,2026,28,1,02:45:36,B26 - 9607 - Warrington - St. Helens - Haydock #1,North West,22.150018,53.484525,-2.668900,355710.440384,398853.648712,Glynn.Evans@cadentgas.com,Cadent Surveyor #06 - LM75XVG,RFADS2357,https://pcubed2.eu.picarro.com/Live/Survey/9c2...,2026-07-08 23:34:20.761871
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
808,BD4D080B-1D12-D329-ABD0-39FEB9804E98,P949807,949807EC-5BE2-489E-8BCC-6CEF9171D217,2026-01-27 00:00:00,2026,5,2,04:03:31,B25R2 - Stockport - Stockport - Bramhall North #1,North West,26.964661,53.385922,-2.176427,388362.784017,387689.952420,michaelgreenough@cadentgas.com,Cadent Surveyor #13 - LM75XBK,RFADS2371,https://pcubed2.eu.picarro.com/Live/Survey/cba...,2026-07-08 23:34:20.761871
809,BD4D080B-1D12-D329-ABD0-39FEB9804E98,P983813,98381321-744F-4CAB-B800-A815E8B3F81A,2026-01-27 00:00:00,2026,5,2,04:03:24,B25R2 - Stockport - Stockport - Bramhall North #1,North West,23.120044,53.386288,-2.176045,388388.299752,387730.596981,michaelgreenough@cadentgas.com,Cadent Surveyor #13 - LM75XBK,RFADS2371,https://pcubed2.eu.picarro.com/Live/Survey/cba...,2026-07-08 23:34:20.761871
810,BD4D080B-1D12-D329-ABD0-39FEB9804E98,P0575F8,0575F8A3-1708-4DCA-8E4A-9B1B3E3F512E,2026-01-11 00:00:00,2026,2,1,21:17:33,B25 - Rayleigh - Rochford - Hullbridge,North London,35.051292,51.616920,0.612224,580944.982702,194131.356162,fatih.gun@cadentgas.com,Cadent Surveyor #01 - LO75ZDT,RFADS2176,https://pcubed2.eu.picarro.com/Live/Survey/773...,2026-07-08 23:34:20.761871
811,BD4D080B-1D12-D329-ABD0-39FEB9804E98,PB12432,B124328F-3C6C-4507-8A8C-1109009736C3,2026-01-09 00:00:00,2026,2,1,00:14:27,B25 - Rayleigh - Rochford - Hullbridge,North London,23.829567,51.612550,0.608504,580704.807834,193636.177083,fatih.gun@cadentgas.com,Cadent Surveyor #01 - LO75ZDT,RFADS2176,https://pcubed2.eu.picarro.com/Live/Survey/635...,2026-07-08 23:34:20.761871
812,BD4D080B-1D12-D329-ABD0-39FEB9804E98,P92BA04,92BA0431-CA07-4943-BD34-A363AFAB44AE,2026-01-06 00:00:00,2026,2,1,00:36:23,B25 - Wembley - Barnet - Mill Hill #1,North London,51.074631,51.622277,-0.240763,521882.283429,192960.670200,Nadeem.hussain@cadentgas.com,Cadent Surveyor #03 - LO75GFG,RFADS2178,https://pcubed2.eu.picarro.com/Live/Survey/09f...,2026-07-08 23:34:20.761871

In [5]:
Query(query = "SELECT * FROM KPI_OutputExcelLocation").execute(KPIHub_Conn)

,CustomerId,BoxFolderId,LastUpdated
0,BD4D080B-1D12-D329-ABD0-39FEB9804E98,370307867916,2026-07-08 23:31:41.201760

In [7]:
Query(query = "SELECT DISTINCT KPIId FROM KPI_Data").execute(KPIHub_Conn)

                             KPIId
0                          FOVMain
1              ReportAssetLengthKm
2             AssetCoveredLengthKm
3               DistributionPipeKm
4        DistributionPipeCoveredKm
5                    ServicePipeKm
6             ServicePipeCoveredKm
7                      ReportCount
8                        LisaCount
9                     EmissionRate
10                         B0Count
11                         B1Count
12                        Bm1Count
13                        Bm2Count
14                         NGCount
15                         PGCount
16                     Not_NGCount
17                     LisaDensity
18            InstatanoeusEmission
19                       B0Density
20                       B1Density
21                      Bm1Density
22                      Bm2Density
23                       NGDensity
24                       PGDensity
25                         B0Share
26                         B1Share
27                        Bm1Share
28                        Bm2Share
29                         NGShare
30                         PGShare
31                     Not_NGShare
32             SurveyDurationHours
33             TargetDurationHours
34             CustomerUtilization
35            StarndardUtilization
36                  TotalSurveyors
37         ProductivityPerSurveyor
38                     SurveyCount
39                      AvgSpeedKm
40                   SurveysCarDay
41                        IdleTime
42                       DaysCount
43             TotalDrivenLengthKm
44                    DrivingRatio
45               NightDrivenLength
46                 DayDrivenLength
47                      NightRatio
48                        DayRatio
49               PeakAboveSATCount
50  CumulativeAssetCoveredLengthKm
51                             POR
52               CurrentCompletion